name: HubSpot Project Upload
author: HubSpot
description: Upload files to your HubSpot Project
branding:
  icon: "upload-cloud"
  color: "orange"
inputs:
  account_id:
    description: Target HubSpot account (Should be stored in secrets)
    required: true
  personal_access_key:
    description: HubSpot personal access key (Should be stored in secrets)
    required: true
runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "22.x"
    - name: Project Upload
      env:
        HUBSPOT_ACCOUNT_ID: ${{ inputs.account_id }}
        HUBSPOT_PERSONAL_ACCESS_KEY: ${{ inputs.personal_access_key }}
      run: |
        npx --yes --package=@hubspot/cli@7.7.0-experimental.2 --call='hs project upload --force-create --use-env'
      shell: bash
