
name: HubSpot Project Upload
author: HubSpot
description: Upload files to your HubSpot Project
branding:
  icon: 'upload-cloud'
  color: 'orange'
inputs:
  account_id:
    description: Target HubSpot account (Should be stored in secrets)
    required: true
  personal_access_key:
    description: HubSpot personal access key (Should be stored in secrets)
    required: true
runs:
  using: "composite"
  steps:
    - name: Install NPM deps
      run: npm install
      shell: bash
    - name: Where are Me
      run: echo $(ls)
      shell: bash
    - name: Where Am I
      run: ls
      shell: bash
    - name: Upload Project
      env:
        HUBSPOT_PORTAL_ID: ${{ inputs.account_id}}
        HUBSPOT_PERSONAL_ACCESS_KEY: ${{ inputs.personal_access_key }}
      run: |
        npx @hubspot/cli@3.0.9-beta.2 project upload --debug --use-env
      shell: bash
