
on: [push]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Access resources directory
        run: cd resources
      - name: HubSpot Project Upload Action
        uses: ./
        with:
          account_id: ${{ secrets.hubspot_account_id }}
          personal_access_key: ${{ secrets.hubspot_personal_access_key }}
